INCLUDES += -I$(PKGDIRBASE)/jerryscript/jerry-core/include
INCLUDES += -I$(PKGDIRBASE)/jerryscript/jerry-ext/include
INCLUDES += -isystem$(RIOTPKG)/jerryscript/include

ARCHIVES += $(BINDIR)/jerryscript.a
ARCHIVES += $(BINDIR)/jerryscript-ext.a
ARCHIVES += $(BINDIR)/jerryscript-port-default.a

DIRS += $(RIOTPKG)/jerryscript/contrib

# Ensure MCPU is correctly exported to CMake variables when configuring the
# Jerrycript build
$(call target-export-variables,libjerry,MCPU)
