IWASM_CORE := $(PKGDIRBASE)/wamr/core
IWASM_ROOT := $(IWASM_CORE)/iwasm
SHARED_LIB_ROOT := $(IWASM_CORE)/shared

IWASM_INCLUDES += ${IWASM_ROOT}/include \
                   ${SHARED_LIB_ROOT}/platform/include \
                   ${SHARED_LIB_ROOT}/platform/riot \
                   #

INCLUDES += $(addprefix -I,${IWASM_INCLUDES})
INCLUDES += -isystem$(PKGDIRBASE)/wamr
INCLUDES += -isystem$(RIOTPKG)/wamr/include

ARCHIVES += $(BINDIR)/libwamr.a

DIRS += $(RIOTPKG)/wamr/contrib

# clang stumbles upon the asm syntax, likely it ignores -mthumb
TOOLCHAINS_BLACKLIST += llvm
